version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT_1802ProjProject
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_git_1802proj.integrations:Sum
  packages:
  - name: SIQA_GIT_1802ProjProject
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2105
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2105
- serviceName: project.siqa_git_1802proj.integrations:deepclonetest
  packages:
  - name: SIQA_GIT_1802ProjProject
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2105
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2105
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2105
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2105
- serviceName: project.siqa_git_1802proj.integrations:testjms
  packages:
  - name: SIQA_GIT_1802ProjProject
    version: "1.0"
- serviceName: publisher:publisher
  packages:
  - name: JMSTest
    version: "1.0"
- serviceName: pub.jms:send
  packages:
  - name: WmPublic
    version: 11.1.0.0.2105
- serviceName: jms2wayssl_publisher:jms2wayssl_publisher
  packages:
  - name: JMS2waySSL
    version: "1.0"
- serviceName: SSL_JDBC_Test.services:insert_ssl
  packages:
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
